
// Apply the groovy plugin to add support for Groovy
apply plugin: 'groovy'
apply plugin: 'application'

// In this section you declare where to find the dependencies of your project
repositories {
    jcenter()
}

// In this section you declare the dependencies for your production and test code
dependencies {
    // We use the latest groovy 2.x version for building this library
    compile 'org.codehaus.groovy:groovy-all:2.4.3'

    // We use the awesome Spock testing and specification framework
    testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
    testCompile 'junit:junit:4.12'
    testCompile 'cglib:cglib-nodep:2.2'       // For mocking classes
    testCompile 'org.objenesis:objenesis:1.2' // For mocking final classes
}

jar {
    manifest {
        attributes 'Main-Class': 'com.xala3pa.twitter.TwitterLauncher'
    }
}


mainClassName = 'com.xala3pa.twitter.TwitterLauncher'
